### ISSUE TITLE
CLI isn't working with environment.yaml

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/ExampleNotebooks#5]
we're getting these errors on binder when calling `openfe --help`

```
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/openfe", line 5, in <module>
    from openfecli.cli import main
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/openfecli/__init__.py", line 5, in <module>
    from . import commands
ImportError: cannot import name 'commands' from partially initialized module 'openfecli' (most likely due to a circular import) (/srv/conda/envs/notebook/lib/python3.9/site-packages/openfecli/__init__.py)
```

**Comment by richardjgowers** [comment]
Yeah I had this before too - https://github.com/OpenFreeEnergy/openfe/pull/57#pullrequestreview-8889151681

**Comment by richardjgowers** [comment]
Ok I pushed up a temporary fix for now
