### ISSUE TITLE
PDB file format issue when read in the first step (I guess )

### ISSUE THREAD

**Issue by wenchangzhou-qtx** [OpenFreeEnergy/ExampleNotebooks#77]
Hey,

I tried on another dataset (cdk2) from https://github.com/openforcefield/protein-ligand-benchmark, the receptor and ligand files are located here https://github.com/openforcefield/protein-ligand-benchmark/tree/main/data/cdk2, it seems the protein residues do not start from 1 but from -1 for ACE instead, not sure if this is the reason to cause the issue when I run the first step. The error is below:
`RBFE-NETWORK PLANNER
______________________

Parsing in Files: 
	Got input: 
		Small Molecules: SmallMoleculeComponent(name=lig_20) SmallMoleculeComponent(name=lig_1oi9) SmallMoleculeComponent(name=lig_26) SmallMoleculeComponent(name=lig_1oiu) SmallMoleculeComponent(name=lig_1h1q) SmallMoleculeComponent(name=lig_21) SmallMoleculeComponent(name=lig_22) SmallMoleculeComponent(name=lig_1h1r) SmallMoleculeComponent(name=lig_17) SmallMoleculeComponent(name=lig_1oiy)
Traceback (most recent call last):
  File "/hpc/users/wenchangzhou/softwares/mambaforge3/envs/openfe_env/bin/openfe", line 10, in <module>
    sys.exit(main())
  File "/hpc/users/wenchangzhou/softwares/mambaforge3/envs/openfe_env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/hpc/users/wenchangzhou/softwares/mambaforge3/envs/openfe_env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/hpc/users/wenchangzhou/softwares/mambaforge3/envs/openfe_env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/hpc/users/wenchangzhou/softwares/mambaforge3/envs/openfe_env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/hpc/users/wenchangzhou/softwares/mambaforge3/envs/openfe_env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/hpc/users/wenchangzhou/softwares/mambaforge3/envs/openfe_env/lib/python3.10/site-packages/openfecli/utils.py", line 61, in wrapper
    result = function(*args, **kwargs)
  File "/hpc/users/wenchangzhou/softwares/mambaforge3/envs/openfe_env/lib/python3.10/site-packages/openfecli/commands/plan_rbfe_network.py", line 136, in plan_rbfe_network
    protein = PROTEIN.get(protein)
  File "/hpc/users/wenchangzhou/softwares/mambaforge3/envs/openfe_env/lib/python3.10/site-packages/plugcli/params.py", line 61, in get
    return self.getter(user_input, context)
  File "/hpc/users/wenchangzhou/softwares/mambaforge3/envs/openfe_env/lib/python3.10/site-packages/plugcli/params.py", line 108, in __call__
    found = strategy(user_input, context)
  File "/hpc/users/wenchangzhou/softwares/mambaforge3/envs/openfe_env/lib/python3.10/site-packages/openfecli/parameters/protein.py", line 25, in _load_protein_from_pdbx
    return ProteinComponent.from_pdbx_file(user_input)
  File "/hpc/users/wenchangzhou/softwares/mambaforge3/envs/openfe_env/lib/python3.10/site-packages/gufe/components/proteincomponent.py", line 121, in from_pdbx_file
    openmm_PDBxFile = PDBxFile(pdbx_file)
  File "/hpc/users/wenchangzhou/softwares/mambaforge3/envs/openfe_env/lib/python3.10/site-packages/gufe/vendor/pdb_file/pdbxfile.py", line 83, in __init__
    block = data[0]
IndexError: list index out of range
`

**Comment by richardjgowers** [comment]
hi @wenchangzhou-qtx 

the error message you're getting is confusing I'll admit.  I did some digging, the CDK2 protein structure has some nonstandard residues (TPO) and these aren't currently handled by the CLI interface.

If you're particularly interested in this system I could show you how to run this via the Python interface instead?

**Comment by wenchangzhou-qtx** [comment]
Hey @richardjgowers,

Thanks for taking a check at this issue, this residue TPO seems be interacting with a bunch of arginines, I might need to keep this interaction. So yes, if there is a way to run it, please guide me from here, thanks!

**Comment by richardjgowers** [comment]
@wenchangzhou-qtx I've adapted our Python tutorial notebook to handle the cdk2 inputs you've linked here: https://gist.github.com/richardjgowers/fe00284753259241f16da1995f396c4e

Testing this locally I found a small bug so you'll have to make sure to update to v0.9.2 of gufe to make this work (run `mamba update -c conda-forge gufe`)
